### ISSUE TITLE
Revamp lecture order

### ISSUE THREAD

**Issue by freddiev4** [bualpha/fall-lectures#4]
- First week should just be intro to quant finance
   - Add a section that talks about what we hope people will get out of the lectures
- Second week is Python & Research

**Comment by FreddieV4** [comment]
For future reference ^^

**Comment by FreddieV4** [comment]
- Keep to 1 hour in length

**Comment by freddiev4** [comment]
Added revamp in #9.

- First week should be short intro to Quant Finance & what we're covering
